version: '3.8'

services:
  travelo-database:
    image: localhost:5000/mysql:latest
    container_name: travelo-database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - travelo-network

  travelo-backend:
    image: localhost:5000/travelo-backend:1.0
    container_name: travelo-backend
    restart: on-failure  # Retry until DB ready
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - travelo-database
    networks:
      - travelo-network

  travelo-frontend:
    image: localhost:5000/travelo-frontend:v1.0
    container_name: travelo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - travelo-backend
    networks:
      - travelo-network

networks:
  travelo-network:
    driver: bridge
